[project]
name = "scratch-llm"
version = "0.1.0"
description = "Educational implementation of an autoregressive LLM"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
